// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

type MenuInput struct {
	ItemName      string `json:"itemName"`
	Price         int    `json:"price"`
	IsStopSelling bool   `json:"isStopSelling"`
}

type User struct {
	ID string `json:"id"`
}
